export const sizes = {
  width: {
    fit: 'fit-content',
    auto: 'auto',
    xs: '1rem',
    sm: '3rem',
    md: '5rem',
    lg: '15rem',
    full: '100%',
  },
  height: {
    fit: 'fit-content',
    auto: 'auto',
    xs: '0.5rem',
    sm: '1rem',
    md: '1.5rem',
    lg: '2rem',
    full: '100%',
  },
  components: {
    avatar: {
      fit: 'fit-content',
      auto: 'auto',
      xs: '20px',
      sm: '30px',
      md: '40px',
      lg: '60px',
      full: '100%',
    },
    button: {
      fit: 'fit-content',
      auto: 'auto',
      xs: '100px',
      sm: '120px',
      md: '140px',
      lg: '160px',
      full: '100%',
    },
  },
}
