export const SET_CANVAS_VALUE = 'SET_CANVAS_VALUE'
export const SET_POSITION_X = 'SET_POSITION_X'
export const SET_POSITION_Y = 'SET_POSITION_Y'
export const SET_CALLBACKS_CANVAS = 'SET_CALLBACKS_CANVAS'
