export const SET_CANVAS_VALUE = 'SET_CANVAS_VALUE'
export const SET_CALLBACKS_CANVAS = 'SET_CALLBACKS_CANVAS'
export const SET_CURRENT_DIRECTION = 'SET_CURRENT_DIRECTION'
export const SET_DIRS = 'SET_DIRS'

