export const SET_SURVEY_OPTION_SELECTED = 'SET_SURVEY_OPTION_SELECTED'

export const SET_CALLBACKS = 'SET_CALLBACKS'

export const SET_PERCENT = 'SET_PERCENT'

export const SET_TOTAL_QUESTIONS = 'SET_TOTAL_QUESTIONS'

export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION'