name: Deploying Repo

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js v15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Lint code
        run: yarn lint
      - name: Build storybook
        run: yarn build-storybook

  visual:
    name: Vistual testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js v15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Build storybook
        run: yarn build-storybook
      - name: Publish in Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: 'storybook-static'
